import {
  Apple,
  Baby,
  Bike,
  Blocks,
  BookHeart,
  BookOpen,
  Brush,
  Bus,
  Calculator,
  Drama,
  GraduationCap,
  HandHeart,
  Heart,
  Languages,
  Leaf,
  MoonStar,
  Music,
  Palette,
  Puzzle,
  School,
  Shapes,
  ShieldCheck,
  Sprout,
  Star,
  Sun,
  Trees,
  Users,
  Utensils,
  type LucideIcon,
} from "lucide-react";

/**
 * Ikon yang boleh dipilih di CMS untuk program dan keunggulan (B7). Kunci
 * mengikuti nama ikon lucide berformat kebab, sama dengan nilai `ikon` di
 * pengaturan. Nama di luar daftar ini tidak ditampilkan.
 */
export const IKON_CMS: Record<string, LucideIcon> = {
  apple: Apple,
  baby: Baby,
  bike: Bike,
  blocks: Blocks,
  "book-heart": BookHeart,
  "book-open": BookOpen,
  brush: Brush,
  bus: Bus,
  calculator: Calculator,
  drama: Drama,
  "graduation-cap": GraduationCap,
  "hand-heart": HandHeart,
  heart: Heart,
  languages: Languages,
  leaf: Leaf,
  "moon-star": MoonStar,
  music: Music,
  palette: Palette,
  puzzle: Puzzle,
  school: School,
  shapes: Shapes,
  "shield-check": ShieldCheck,
  sprout: Sprout,
  star: Star,
  sun: Sun,
  trees: Trees,
  users: Users,
  utensils: Utensils,
};

/** Nama ikon untuk pembaca layar dan tooltip di pemilih ikon CMS. */
export const LABEL_IKON_CMS: Record<keyof typeof IKON_CMS, string> = {
  apple: "Apel",
  baby: "Bayi",
  bike: "Sepeda",
  blocks: "Balok mainan",
  "book-heart": "Buku dan hati",
  "book-open": "Buku terbuka",
  brush: "Kuas",
  bus: "Bus",
  calculator: "Kalkulator",
  drama: "Topeng drama",
  "graduation-cap": "Topi wisuda",
  "hand-heart": "Tangan dan hati",
  heart: "Hati",
  languages: "Bahasa",
  leaf: "Daun",
  "moon-star": "Bulan bintang",
  music: "Musik",
  palette: "Palet warna",
  puzzle: "Puzzle",
  school: "Sekolah",
  shapes: "Bentuk",
  "shield-check": "Perisai",
  sprout: "Tunas",
  star: "Bintang",
  sun: "Matahari",
  trees: "Pohon",
  users: "Orang",
  utensils: "Alat makan",
};
